version: "3"
services:
  #Web 
  template-web:
    container_name: template-web
    build: ./setup
    privileged: true
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
    depends_on:
      - template-db
    tty: true
    stdin_open: true

  # MySQL
  template-db:
    image: mariadb:latest
#    image: mysql:5.7
    restart: always
    container_name: template-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: templatedb
      MYSQL_USER: templatedbuser
      MYSQL_PASSWORD: templatedbpass
      MYSQL_START_TIMEOUT: 1200000
      TZ: 'Asia/Tokyo'
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/data:/var/lib/mysql
#      - ./database/mysql_conf/:/etc/mysql/conf.d
#      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/log/mysql:/var/log/mysql
    ports:
      - 3306:3306
#    deploy:
#      resources:
#        limits:
#          memory: 1g

  # phpmyadmin
  template-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: template-db
      PMA_USER: templatedbuser
      PMA_PASSWORD: templatedbpass
      PMA_PORT: 3306
    links:
      - template-db
    ports:
      - 8080:80
    volumes:
    #  - ../src/phpMyAdmin/sessions:/sessions
      - ./phpMyAdmin/sessions:/sessions
    depends_on:
      - template-db